### ISSUE TITLE
Throw an error before working long hours

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-autotuning#37]
Reported by @w-simon . The last fix caused problems in other pipelines, so I reverted the patch and we need to check where the problem happens. To reproduce:

We test according to the method described in the documentation(https://github.com/ctuning/ck/wiki/Autotuning).

$ rm _setup_program_pipeline_tmp.json
$ ck pipeline program:cbench-automotive-susan --cmd_key=edges --compiler_description_uoa=gcc-44x --prepare --save_to_file=_setup_program_pipeline_tmp.json
$ ck autotune pipeline:program pipeline_from_file=_setup_program_pipeline_tmp.json record=yes
The program runs for a while, but at the end, this error occurs:

CK error: [pipeline] meta is not defined - can't aggregate!

**Comment by gfursin** [comment]
Hi @w-simon. I checked your way of starting autotuning and the way I described it in https://github.com/ctuning/ck/wiki/Autotuning , and I found that there is no bug, but you just forgot a few things:

First of all you need to use GCC descriptions which has "-auto" at the end, so instead of gcc-44x, you need to use gcc-4.4.0-auto as follows:
```
$ ck pipeline program:cbench-automotive-susan --cmd_key=edges --compiler_description_uoa=gcc-4.4.0-auto --prepare --save_to_file=_setup_program_pipeline_tmp.json
```
You can also add flag --no_state_check if you CPU frequency is unstable and you want to skip validation of frequency between autotuning iterations.

Second, you should add autotuning configuration file as described in https://github.com/ctuning/ck/wiki/Autotuning#autotuning-program-and-recording-experiments-via-ck

i.e.
$ cat > autotuning_configuration.json

 {
  "choices_order": [
    ["##compiler_flags#*"]
  ],
  "choices_selection": [
     {"type":"random", "omit_probability":"0.90", "tags":"basic,optimization", "notags":""}
  ],
  "pipeline_update":{
     "repeat":200,
     "select_best_base_flag_for_first_iteration":"yes"
   },
  "seed":12345,
  "iterations":10,
  "repetitions":3,
  "record":"yes",
  "record_uoa":"demo-autotune-flags-susan-linux-i10",
  "tags":"my experiments,autotuning,compiler flags,gcc 5.1",
  "record_params": {
    "search_point_by_features":"yes"
  },
  "features_keys_to_process":["##choices#*"]
 }

 Ctrl^D

and only then start autotuning:
```
ck autotune pipeline:program pipeline_from_file=_setup_program_pipeline_tmp.json @autotuning_configuration.json
```

In such case CK will prepare all meta and will record experiments. I checked it right now and it worked on my Ubuntu machine with GCC 8.1.0

By the way, note that we automated all above steps with so called autotuning "scenarios", i.e, if you run 
```
$ ck autotune program:cbench-automotive-susan
```
you can select autotuning scenario and CK should prepare pipeline, run experiments, check multi-objective constraints and record experiments.

Hope it's of help and thanks a lot for your feedback!

**Comment by taskset** [comment]
Hi gfursin,  thank you very much.
With your help, we can run the autotuning scenario.
Since we were in the National Day holiday, we did not respond to the verification results in time, I am sorry.
We will continue to apply ck-autotuning more widely in our projects, thank you!
Regards,


发件人: Grigori Fursin <notifications@github.com>
发送时间: 2018年10月1日 15:51
收件人: ctuning/ck-autotuning
抄送: Wen Yang; Mention
主题: Re: [ctuning/ck-autotuning] Throw an error before working long hours (#37)

Hi @w-simon<https: github.com="" w-simon="">. I checked your way of starting autotuning and the way I described it in https://github.com/ctuning/ck/wiki/Autotuning , and I found that there is no bug, but you just forgot a few things:

First of all you need to use GCC descriptions which has "-auto" at the end, so instead of gcc-44x, you need to use gcc-4.4.0-auto as follows:

$ ck pipeline program:cbench-automotive-susan --cmd_key=edges --compiler_description_uoa=gcc-4.4.0-auto --prepare --save_to_file=_setup_program_pipeline_tmp.json


You can also add flag --no_state_check if you CPU frequency is unstable and you want to skip validation of frequency between autotuning iterations.

Second, you should add autotuning configuration file as described in https://github.com/ctuning/ck/wiki/Autotuning#autotuning-program-and-recording-experiments-via-ck

i.e.
$ cat &gt; autotuning_configuration.json

{
"choices_order": [
["##compiler_flags#"]
],
"choices_selection": [
{"type":"random", "omit_probability":"0.90", "tags":"basic,optimization", "notags":""}
],
"pipeline_update":{
"repeat":200,
"select_best_base_flag_for_first_iteration":"yes"
},
"seed":12345,
"iterations":10,
"repetitions":3,
"record":"yes",
"record_uoa":"demo-autotune-flags-susan-linux-i10",
"tags":"my experiments,autotuning,compiler flags,gcc 5.1",
"record_params": {
"search_point_by_features":"yes"
},
"features_keys_to_process":["##choices#"]
}

Ctrl^D

and only then start autotuning:

ck autotune pipeline:program pipeline_from_file=_setup_program_pipeline_tmp.json @autotuning_configuration.json


In such case CK will prepare all meta and will record experiments. I checked it right now and it worked on my Ubuntu machine with GCC 8.1.0

By the way, note that we automated all above steps with so called autotuning "scenarios", i.e, if you run

$ ck autotune program:cbench-automotive-susan


you can select autotuning scenario and CK should prepare pipeline, run experiments, check multi-objective constraints and record experiments.

Hope it's of help and thanks a lot for your feedback!

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https: github.com="" ctuning="" ck-autotuning="" issues="" 37#issuecomment-425959206="">, or mute the thread<https: github.com="" notifications="" unsubscribe-auth="" aamuon08jlfhk_now8bzgpbyc7kwtjpzks5ugjoqgajpzm4xcsjk="">.
</https:></https:></https:></notifications@github.com>

**Comment by gfursin** [comment]
Sure, @w-simon! You are welcome and good luck with you autotuning R&D!
