### ISSUE TITLE
Error "Problem accessing CK server: CK error: name is empty in platform information exchange" in android app

### ISSUE THREAD

**Issue by alkedr** [ctuning/ck-autotuning#9]
I installed this android app: https://play.google.com/store/apps/details?id=openscience.crowdsource.experiments, pressed "start" and got this error:
![Screenshot](https://pp.vk.me/c633316/v633316962/173fd/mbhqgRahUGk.jpg)

**Comment by gfursin** [comment]
Ups! Thanks for noting - I think I know the problem and will try to fix it within a few days ...

**Comment by gfursin** [comment]
I think I fixed the Android app and uploaded the new version. However, I just realized that you are using Intel-based Android. At the moment, I compile code for ARM processors only. However, it should not be very difficult to do it for x86. Since I don't have Intel-based Android mobile phones, I may need to ask you to test it when ready. Thanks!

**Comment by alkedr** [comment]
The old error is gone, now I see an error about unsupported ABI.
Yes, feel free to contact me when x86 support is ready. :)

**Comment by gfursin** [comment]
Cool! Thanks a lot!

**Comment by gfursin** [comment]
Hi again! I think I added support for both x86 and x86_64 on CK server side (GCC 4.9 & LLVM 3.6 from Android NDK). It seems to be compiling fine, but again, I can't check if it runs ;) . Do you mind to try it, please? Thanks a lot!

**Comment by alkedr** [comment]
![Screenshot](https://pp.vk.me/c621821/v621821962/3976c/sQpTjdAsOJU.jpg)

**Comment by gfursin** [comment]
Thanks again for trying. Seems like compilation logic works fine on CK server side, but since I produce dynamic libs, maybe some lib is missing. I updated Android app again (1.3) to print error output. Sorry for bothering you again, but may I ask you to run it again, please. 

If error is unclear, I also attached zip with binaries produced at CK. Maybe you can run one of them manually via ADB - you should normally see if there is a missing lib or something else?..

[crowd-pack.zip](https://github.com/ctuning/ck-autotuning/files/166059/crowd-pack.zip)

Thanks a lot again and sorry for bothering - it's difficult to debug such cases without actually having a platform ;) ...

**Comment by alkedr** [comment]
Yeah, feel free to ask me to run it again, that's no problem.

The execution log didn't change, still "Error: execution failure!".

I tried to run it via ADB:

```
shell@Z00A:/ $ ls -l /data/local/tmp                                           
-rwxrwxrwx shell    shell       38168 2016-03-09 19:18 a-5af75dd9993d7788.out
-rwxrwxrwx shell    shell       38536 2016-03-09 19:18 a-cb3389da5076f4b7.out
-rwxrwxrwx shell    shell      270015 2016-03-09 19:18 data.pgm
-rwxrwxrwx shell    shell       12632 2016-03-09 19:18 librtlxopenme.so
shell@Z00A:/ $ /data/local/tmp/a-5af75dd9993d7788.out                          
/system/bin/sh: /data/local/tmp/a-5af75dd9993d7788.out: No such file or directory
1|shell@Z00A:/ $ /data/local/tmp/a-cb3389da5076f4b7.out                        
/system/bin/sh: /data/local/tmp/a-cb3389da5076f4b7.out: No such file or directory
1|shell@Z00A:/ $
```

The files are there, the permissions seem to be fine, `more /data/local/tmp/a-5af75dd9993d7788.out` works.
I don't know what a missing dynamic lib error looks like on android. If it's still possible that this is caused by missing dynamic lib, we could try building a static version.

**Comment by gfursin** [comment]
Hmm, actually, I searched through Internet and found that it's sadly not as straightforward to compile and run native program on this Intel processor as I thought:
- https://together.jolla.com/question/66098/jolla-tablet-support-for-android-apps-utilizing-the-ndk/
- http://www.androidcentral.com/asus-zenfone-2-review

So, I added static flag and also retargeted compilation to API 19 + 32 bits. Can you please try if it works, by chance? 
If not, I think I will have to postpone such support until I get a similar platform locally and test it more thoroughly ... I will also need to check how to detect CPU cores and frequency for this processor (standard way doesn't see to work)... Thanks a lot!

**Comment by alkedr** [comment]
It works! I have run it a few times. Can you see the results on the server side?

**Comment by gfursin** [comment]
Wow, cool! Yes, I see logging for generated optimizations for your device. Good optimization cases were not yet found, but it usually takes some time (10-20 iterations on ARM). May I ask you just one more thing: I removed 'static' flag and will try to compile programs dynamically again - I just think that maybe the problem was in problematic x86_64 so reverting to x86 may solve the problem. Do you mind to try it again, please? If it fails, I will move 'static' flag back! Thanks a lot again!!!

**Comment by alkedr** [comment]
Still works.

**Comment by gfursin** [comment]
I actually saw that after I committed new version, I didn't get stats, so I reverted back to static flag and it started working. I will keep this flag. Thanks a lot again for your help and feedback. I will close this ticket!
